## Thanks to https://dev.to/thibaultduponchelle/a-tour-of-perl-github-actions-44lp
name: CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  Perl:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.32"

      # Runs a single command using the runners shell
      - name: Check syntax
        run: for f in `find . -name "*.pl"`; do perl -c $f; done
